name: W*S*F
favicon: null
layout_spectrum: 0.24291
typography_spectrum: 0.56428
title: With Some Friends
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f1f1f1'
    - '#dbdbdb'
    - '#cdcdcd'
    - '#bcbcbc'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
