name: W/$/F
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56428
title: With Some Friends
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeeeee'
    - '#000004'
    - '#a00004'
    - '#8a3a23'
    - '#706a8b'
  brandStrength: 0.8514826830942184
  lightness: 0.9643030161969364
  saturation: 0.4819506553467363
  rhythmicContrast: 0.321724722860381
purpose: []
